name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - master  # Cambia a main si tu repositorio usa main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Ajusta la versión si es necesario

      - name: Install dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --output-path=dist/induservicefl/browser --base-href /induservicefl/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages  # Se creará un branch gh-pages
          folder: dist/induservicefl/browser  # Carpeta de salida del build